// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ9dntwGgD0U2D97ZcDqkWy6-G8thGyOA',
    appId: '1:662803436661:web:bafb46346bfc47dbb1143c',
    messagingSenderId: '662803436661',
    projectId: 'riza-property',
    authDomain: 'riza-property.firebaseapp.com',
    storageBucket: 'riza-property.appspot.com',
    measurementId: 'G-T8RE9FXEXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_S7OD6uUjzM1CE4GJd7WlGQ9mQlI2KtA',
    appId: '1:662803436661:android:5b354fa7870e27ceb1143c',
    messagingSenderId: '662803436661',
    projectId: 'riza-property',
    storageBucket: 'riza-property.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiCQ8U8MZvRZUA1xTv-IsDD23Ws3JDquQ',
    appId: '1:662803436661:ios:2fd1911d3cc30134b1143c',
    messagingSenderId: '662803436661',
    projectId: 'riza-property',
    storageBucket: 'riza-property.appspot.com',
    iosBundleId: 'com.example.rizaProperty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiCQ8U8MZvRZUA1xTv-IsDD23Ws3JDquQ',
    appId: '1:662803436661:ios:2fd1911d3cc30134b1143c',
    messagingSenderId: '662803436661',
    projectId: 'riza-property',
    storageBucket: 'riza-property.appspot.com',
    iosBundleId: 'com.example.rizaProperty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ9dntwGgD0U2D97ZcDqkWy6-G8thGyOA',
    appId: '1:662803436661:web:02b053be1795f2a1b1143c',
    messagingSenderId: '662803436661',
    projectId: 'riza-property',
    authDomain: 'riza-property.firebaseapp.com',
    storageBucket: 'riza-property.appspot.com',
    measurementId: 'G-LDBW97WFDF',
  );
}
